### PR TITLE
Update raincatcher documentation 

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Update RainCatcher chapter - point to our website and updated documentation.

Udate on feedhenry.org page to no longer list our modules (it will just point to our webpage with documentation

### CODE REVIEW

**Comment by wtrocki** [comment]
Build is failing due to external links from other content/

**Review by austincunningham — COMMENTED** [review]
Looks like the Raincatcher logo is a dead link.

**Comment by wtrocki** [comment]
@austincunningham This will be rendered and will work in the website. Preview will not work.
I did not changed that and it works on current website.

**Comment by wtrocki** [comment]
@secondsun - it looks like build is failing due to some unrelated issues with links not being available. Can I remove this links?

**Comment by secondsun** [comment]
Try this first : https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-284475461

Looks like Travis has outdated certs.

**Comment by wtrocki** [comment]
@jameelB can you take look on this?

**Comment by secondsun** [comment]
@wtrocki I'm fine with either removing the links or adding them to a whitelist.  It sounded like from the issue that updating Ubuntu would work but it does not and it isn't *that* important.

**Review by witmicko — APPROVED** [review]
looks good

**Pull request merged**
